spring.application.name=Project03-OrderManagement

# Database
spring.datasource.url=jdbc:mysql://localhost:3306/order_management
spring.datasource.username=root
spring.datasource.password=java1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# JSP View Resolver
spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp
